### ISSUE TITLE
Add timeout when waiting for a process to Stop

### ISSUE THREAD

**Issue by Bo0mer** [mokiat/gocrane#11]
I have a weird process that somehow refuses to stop, which leads to the following logs:

```text
16:23:22 [gocrane]: building...
16:23:26 [gocrane]: build was successful.
16:23:26 [gocrane]: stopping running process...
16:23:26 [program]: {"logtype":"system","message":"Shutting down due to signal: terminated","severity":"INFO"}
16:23:27 [program]: {"logtype":"system","message":"HTTP server stopped","severity":"INFO"}
16:23:27 [program]: bye...
```

And everything halts. It took me some time to understand that the program at hand is not actually exiting, although the last statement of the `main` function is `fmt.Println("bye")`. The program is using some `defer`s, that seem to be blocking, but this is hard to catch.

My proposal is to add some timeout when waiting for a process to finish. After the timeout, the process will get killed (-9) and an error message will be printed by gocrane, since this is most likely a bug in the program's shutdown logic (it should not block indefinitely, or at least it should tell why).

**Comment by mokiat** [comment]
Good catch.
