### ISSUE TITLE
Make it possible to configure build and run arguments

### ISSUE THREAD

**Issue by mokiat** [mokiat/gocrane#3]
It should be possible to specify run arguments for the `go` compiler and for the executable.

**Comment by mokiat** [comment]
Wrong issue

**Comment by Bo0mer** [comment]
With #13 it is now possible to configure run arguments.

Still, it is not yet possible to configure build arguments (arguments that will be passed to the `go build` command), so I'll leave this open.

**Comment by Bo0mer** [comment]
With #14 we can close this. Hooray!
